In [1]:
# Import necessary packages
import pandas as pd

### Exploring the Data

In [2]:
# Read in dataset
df = pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
# Look the number of rows each feature has & the data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
# Check summary statistics
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,1950.500000,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,44.068462,15.207589,18.0,31.00,44.0,57.00,70.0
Purchase Amount (USD),3900.0,59.764359,23.685392,20.0,39.00,60.0,81.00,100.0
Review Rating,3863.0,3.750065,0.716983,2.5,3.10,3.8,4.40,5.0
Previous Purchases,3900.0,25.351538,14.447125,1.0,13.00,25.0,38.00,50.0

Note that the "describe()" method only gives us stats of the *numerical* features. If we want to look the stats for the cateogrical columns, we can do the following:

In [5]:
# Check summary statistics (including categorical features)
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,NaN,NaN,NaN,1950.5,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,NaN,NaN,NaN,44.068462,15.207589,18.0,31.0,44.0,57.0,70.0
Gender,3900,2,Male,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Item Purchased,3900,25,Blouse,171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,3900,4,Clothing,1737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase Amount (USD),3900.0,NaN,NaN,NaN,59.764359,23.685392,20.0,39.0,60.0,81.0,100.0
Location,3900,50,Montana,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,3900,4,M,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Color,3900,25,Olive,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Season,3900,4,Spring,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review Rating,3863.0,NaN,NaN,NaN,3.750065,0.716983,2.5,3.1,3.8,4.4,5.0
Subscription Status,3900,2,No,2847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shipping Type,3900,6,Free Shipping,675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount Applied,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Promo Code Used,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Previous Purchases,3900.0,NaN,NaN,NaN,25.351538,14.447125,1.0,13.0,25.0,38.0,50.0
Payment Method,3900,6,PayPal,677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Frequency of Purchases,3900,7,Every 3 Months,584,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Check missing values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

We can see that "Review Rating" has 37 missing values. We can replace them in a few ways, including either the mean or the median. Generally speaking, it's better to replace it with the median because the mean is affected by outliers, which can skew the distribution of the data.

However, just replacing the missing values with the cumulative review rating median is not good enough. This is because different categories of products might have different review rating systems. For example, ratings for clothing might differ from ratings for shoes; this can introduce bias into the dataset. To overcome this, we will be filling in missing values with the median for each respective category.

In [7]:
# Fill the missing values with the median for each respective category
# (e.g., missing clothes ratings get replaced with the median for only clothes, not anything else) 
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

# Check to see if there are any missing values anymore
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
# Have a standardized naming convention for the column names
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [9]:
df = df.rename(columns=({'purchase_amount_(usd)': 'purchase_amount'}))  # Remove the '(usd)' to standardize name

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

### Feature Engineering

In [10]:
# Create a new column: age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)  # Split ages into 4 different-sized groups, based on data distribution

In [11]:
df[['age', 'age_group']].head(20)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
5    46  Middle-aged
6    63       Senior
7    27  Young Adult
8    26  Young Adult
9    57  Middle-aged
10   53  Middle-aged
11   30  Young Adult
12   61       Senior
13   65       Senior
14   64       Senior
15   64       Senior
16   25  Young Adult
17   53  Middle-aged
18   52  Middle-aged
19   66       Senior

In [12]:
# Create a new column: purchase_frequency_days

# Here, we are going to convert text frequencies into numerical values--makes it easier for analysis later on

# Mappings are done by days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(20)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly
15                       30                Monthly
16                       14              Bi-Weekly
17                       90              Quarterly
18                        7                 Weekly
19                       14              Bi-Weekly

In [14]:
# Look at how the two following columns are related
df[['discount_applied', 'promo_code_used']].head(20)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes
11              Yes             Yes
12              Yes             Yes
13              Yes             Yes
14              Yes             Yes
15              Yes             Yes
16              Yes             Yes
17              Yes             Yes
18              Yes             Yes
19              Yes             Yes

These two columns are very much related. This is because if a promo code was used, then some sort of discount was applied to the purchase. Though sometimes, companies can apply discounts without promo codes (e.g., seasonal sales, exclusive discounts for members, etc.).

So the question is, *Do we need both columns?*

Delve more into the relationship between the two to see the answer...

In [15]:
# See if both columns contain the same information
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

From the code above, we can see that both columns indeed carry the same info. This means one of the columns is redundant. In this case, let's remove `promo_code_used`.

In [16]:
# Remove promo_code_used because it's redundant
df = df.drop('promo_code_used', axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

### Connecting Notebook with PostgreSQL

In [17]:
# Install necessary packages
%pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\r4g\appdata\roaming\python\python314\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\r4g\appdata\roaming\python\python314\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\r4g\appdata\roaming\python\python314\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\r4g\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: C:\Program Files\Python314\python.exe -m pip install --upgrade pip

In [18]:
from sqlalchemy import create_engine

# Connecting to PostgreSQL
username = "postgres"
password = "piis3.14159265359"
host = "localhost"
port = "5432"
database = "Customer_Behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Load the DataFrame into PostgreSQL
table_name = "customer_purchases"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'!")

Data successfully loaded into table 'customer_purchases' in database 'Customer_Behavior'!